/**
 * Codegen: parses /DESIGN.md YAML front matter and emits two files
 *   - frontend/lib/design-tokens.ts (typed constants for tailwind.config.ts)
 *   - frontend/app/globals.css :root block (CSS custom properties)
 *
 * Usage:
 *   pnpm tokens:gen           write the files
 *   pnpm tokens:check         exit 1 if committed files differ from regenerated
 *
 * /DESIGN.md is the binding contract. shadcn/ui defaults are not.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FRONTEND_ROOT = resolve(__dirname, "..");
const DESIGN_MD = resolve(FRONTEND_ROOT, "..", "DESIGN.md");
const TOKENS_TS = resolve(FRONTEND_ROOT, "lib", "design-tokens.ts");
const GLOBALS_CSS = resolve(FRONTEND_ROOT, "app", "globals.css");

const TOKENS_BANNER =
  "// AUTOGENERATED by scripts/generate-design-tokens.ts from /DESIGN.md.\n" +
  "// Do not edit by hand. Re-run `pnpm tokens:gen` after any change to /DESIGN.md.";

const CSS_BEGIN = "/* === BEGIN GENERATED TOKENS === */";
const CSS_END = "/* === END GENERATED TOKENS === */";

type DesignDoc = {
  colors: Record<string, string>;
  typography: Record<
    string,
    {
      fontFamily: string;
      fontSize?: string;
      fontWeight?: number;
      lineHeight?: number;
      letterSpacing?: string;
    }
  >;
  rounded: Record<string, string>;
  spacing: Record<string, string>;
  components: Record<string, Record<string, string | number>>;
};

function extractFrontMatter(md: string): string {
  const match = md.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) throw new Error("No YAML front matter found in DESIGN.md");
  return match[1];
}

function resolveRef(value: unknown, doc: DesignDoc): unknown {
  if (typeof value !== "string") return value;
  const m = value.match(/^\{(.+)\}$/);
  if (!m) return value;
  const path = m[1].split(".");
  let cur: unknown = doc as unknown;
  for (const seg of path) {
    if (cur && typeof cur === "object" && seg in (cur as Record<string, unknown>)) {
      cur = (cur as Record<string, unknown>)[seg];
    } else {
      throw new Error(`Unresolved token reference: ${value}`);
    }
  }
  return resolveRef(cur, doc);
}

function asTsLiteral(v: unknown): string {
  if (typeof v === "string") return JSON.stringify(v);
  if (typeof v === "number") return String(v);
  if (Array.isArray(v)) return `[${v.map(asTsLiteral).join(", ")}]`;
  if (v && typeof v === "object") {
    const entries = Object.entries(v).map(
      ([k, val]) => `${JSON.stringify(k)}: ${asTsLiteral(val)}`,
    );
    return `{ ${entries.join(", ")} }`;
  }
  return JSON.stringify(v);
}

function buildTokensTs(doc: DesignDoc): string {
  // Tailwind theme.colors expects a flat record of name → CSS color.
  const colors: Record<string, string> = { ...doc.colors };

  // fontFamily.mono — JetBrains Mono with monospace fallback chain.
  const fontFamily = {
    mono: [
      "JetBrains Mono",
      "ui-monospace",
      "SFMono-Regular",
      "Menlo",
      "Consolas",
      "monospace",
    ],
  };

  // Tailwind fontSize accepts [size, {lineHeight, letterSpacing, fontWeight}]
  const fontSize: Record<string, [string, Record<string, string | number>]> = {};
  for (const [name, t] of Object.entries(doc.typography)) {
    const meta: Record<string, string | number> = {};
    if (t.lineHeight !== undefined) meta.lineHeight = String(t.lineHeight);
    if (t.fontWeight !== undefined) meta.fontWeight = String(t.fontWeight);
    if (t.letterSpacing !== undefined) meta.letterSpacing = t.letterSpacing;
    fontSize[name] = [t.fontSize ?? "0px", meta];
  }

  const spacing: Record<string, string> = { ...doc.spacing, "0": "0px" };
  const borderRadius: Record<string, string> = { ...doc.rounded };

  // Component tokens (resolved). Useful for owned primitives that need raw values.
  const components: Record<string, Record<string, unknown>> = {};
  for (const [cname, props] of Object.entries(doc.components)) {
    components[cname] = {};
    for (const [pname, pval] of Object.entries(props)) {
      components[cname][pname] = resolveRef(pval, doc);
    }
  }

  return [
    TOKENS_BANNER,
    "",
    "export const colors = " + asTsLiteral(colors) + " as const;",
    "",
    "export const fontFamily = " + asTsLiteral(fontFamily) + " as const;",
    "",
    "export const fontSize = " + asTsLiteral(fontSize) + " as const;",
    "",
    "export const spacing = " + asTsLiteral(spacing) + " as const;",
    "",
    "export const borderRadius = " + asTsLiteral(borderRadius) + " as const;",
    "",
    "export const components = " + asTsLiteral(components) + " as const;",
    "",
    "export type ColorToken = keyof typeof colors;",
    "export type SpacingToken = keyof typeof spacing;",
    "export type FontSizeToken = keyof typeof fontSize;",
    "",
  ].join("\n");
}

function buildCssBlock(doc: DesignDoc): string {
  const lines: string[] = [CSS_BEGIN, ":root {"];
  for (const [name, hex] of Object.entries(doc.colors)) {
    lines.push(`  --color-${name}: ${hex};`);
  }
  for (const [name, val] of Object.entries(doc.spacing)) {
    lines.push(`  --space-${name}: ${val};`);
  }
  for (const [name, val] of Object.entries(doc.rounded)) {
    lines.push(`  --rounded-${name}: ${val};`);
  }
  for (const [name, t] of Object.entries(doc.typography)) {
    if (t.fontSize) lines.push(`  --font-size-${name}: ${t.fontSize};`);
    if (t.fontWeight !== undefined)
      lines.push(`  --font-weight-${name}: ${t.fontWeight};`);
    if (t.lineHeight !== undefined)
      lines.push(`  --line-height-${name}: ${t.lineHeight};`);
    if (t.letterSpacing) lines.push(`  --letter-spacing-${name}: ${t.letterSpacing};`);
  }
  lines.push("}", CSS_END);
  return lines.join("\n");
}

function patchCss(existing: string, generated: string): string {
  const re = new RegExp(
    `${escapeRe(CSS_BEGIN)}[\\s\\S]*?${escapeRe(CSS_END)}`,
    "m",
  );
  if (!re.test(existing)) {
    throw new Error(
      `globals.css is missing the markers ${CSS_BEGIN} / ${CSS_END}. ` +
        `Restore them and re-run.`,
    );
  }
  return existing.replace(re, generated);
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function main() {
  const check = process.argv.includes("--check");

  const md = readFileSync(DESIGN_MD, "utf8");
  const fm = extractFrontMatter(md);
  const doc = parseYaml(fm) as DesignDoc;

  const tokensTs = buildTokensTs(doc);
  const newCssBlock = buildCssBlock(doc);
  const existingCss = readFileSync(GLOBALS_CSS, "utf8");
  const newCss = patchCss(existingCss, newCssBlock);

  if (check) {
    const currentTs = readFileSync(TOKENS_TS, "utf8");
    if (currentTs.trim() !== tokensTs.trim() || existingCss !== newCss) {
      console.error(
        "design-tokens.ts or globals.css is stale. Run `pnpm tokens:gen` and commit.",
      );
      process.exit(1);
    }
    console.log("Tokens up to date.");
    return;
  }

  writeFileSync(TOKENS_TS, tokensTs + "\n");
  writeFileSync(GLOBALS_CSS, newCss);
  console.log(`Wrote ${TOKENS_TS}`);
  console.log(`Patched ${GLOBALS_CSS}`);
}

main();
